# Generated by Django 3.1.7 on 2021-03-13 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.AddField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='times_can_take',
            field=models.IntegerField(default=1),
        ),
    ]
