# Generated by Django 3.1.7 on 2021-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_auto_20210313_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
