# Generated by Django 3.1.7 on 2021-03-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_auto_20210314_1915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='options',
            unique_together={('question', 'user', 'answer')},
        ),
    ]
