# Generated by Django 3.1.7 on 2021-03-20 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_auto_20210318_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='marks',
        ),
        migrations.AddField(
            model_name='question',
            name='question_n_mark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(-250)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
