# Generated by Django 3.1.7 on 2021-03-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0008_auto_20210325_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='belongs',
            unique_together={('user', 'clas')},
        ),
    ]
