# Generated by Django 3.1.7 on 2021-03-27 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0010_auto_20210327_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
