# Generated by Django 3.1.7 on 2021-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0011_takes_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Notification_txt',
            new_name='Notification',
        ),
    ]
