# Generated by Django 3.1.7 on 2021-04-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0012_auto_20210331_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id',)},
        ),
    ]
