# Generated by Django 3.1.7 on 2021-04-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0014_auto_20210401_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makes',
            options={'verbose_name': 'Make', 'verbose_name_plural': 'Makes'},
        ),
        migrations.AlterModelOptions(
            name='takes',
            options={'verbose_name': 'Take', 'verbose_name_plural': 'Takes'},
        ),
    ]
