# Generated by Django 3.1.7 on 2021-04-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0015_auto_20210401_2147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'question_text')},
        ),
    ]
