# Generated by Django 3.1.7 on 2021-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0019_auto_20210406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='takes',
            name='submission',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='takes',
            name='times_taken',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
