# Generated by Django 3.1.7 on 2021-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0021_remove_makes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='submission',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
