# Generated by Django 3.1.7 on 2021-04-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0023_auto_20210406_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('user', 'quiz')},
        ),
    ]
