# Generated by Django 3.1.7 on 2021-04-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0025_auto_20210406_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takes',
            old_name='status',
            new_name='nemail',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizApp.quiz'),
        ),
    ]
