# Generated by Django 3.2.2 on 2021-05-22 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0027_auto_20210522_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='marks',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
