# Generated by Django 3.2.2 on 2021-05-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0028_alter_takes_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_text', 'correct')},
        ),
    ]
