# Generated by Django 3.2.2 on 2021-05-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0029_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_text')},
        ),
    ]
